server.port: 8089

spring:
  application:
      name: elasticjob-demo
  # datasource:
  #   myDataSource:
  #     type: com.zaxxer.hikari.HikariDataSource
  #     driver-class-name: com.mysql.cj.jdbc.Driver
  #     username: root
  #     password: 123123
  #     jdbc-url: jdbc:mysql://127.0.0.1:3306/sampdb?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  #     hikari:
  #       minimum-idle: 5
  #       maximum-pool-size: 20
  #       auto-commit: true
  #       idle-timeout: 30000
  #       pool-name: MysqlHikariCP
  #       max-lifetime: 1800000
  #       connection-timeout: 10000
  #       connection-test-query: SELECT 1

elasticjob:
  regCenter:
    serverLists: 127.0.0.1:2181
    namespace: ${spring.application.name}
    
